## File initially generated by createOverlay
## and then supposedly modified manually.
## Some hints for manual modifications are in the file,
## but the full doc is on nixos / nix packages website:
## https://nixos.org/manual/nixpkgs/stable/#sec-language-coq

{ lib, mkCoqDerivation, which, coq
  ## declare extra dependencies here, to be used in propagateBuildInputs e.g.
  # , mathcomp, coq-elpi
  , version ? null, shim ? false }:

with lib; mkCoqDerivation {
  pname = "template";
  ## you can configure the domain, owner and repository, the default are:
  # repo = "template";
  # owner = "coq-community";
  # domain = "github.com";

  inherit version;
  defaultVersion = with versions; switch coq.coq-version [
    ## Example of possible dependencies
    # { case = range "8.13" "8.14"; out = "1.2.0"; }
    ## other predicates are `isLe v`, `isLt v`, `isGe v`, `isGt v`, `isEq v` etc
  ] null;

  ## Declare existing releases
  ## leave sha256 empty at first and then copy paste
  ## the resulting sha given by the error message
  # release."1.1.1".sha256 = "";
  ## if the tag is not exactly the version number you can amend here
  # release."1.1.1".rev = "1.1.1"; # e.g. `= "v1.1.1"`
  ## perhaps the tags all have a different name, that you can modify it here
  # releaseRev = v: "${v}"; # e.g. `= v: "v${v}"`

  ## Add dependencies in here (declare them first at the begining of the file
  # propagatedBuildInputs = [ ]; ## e.g. `= [ mathcomp coq-elpi ]`

  ## Does the package contain
  # mlPlugin = false;

  ## Give some meta data
  meta = {
    ## Describe your package in one sentence
    # description = "";
    ## Kindly ask one of these people if they want to be a maintainer
    # maintainers = with maintainers; [ cohencyril siraben vbgl Zimmy48 ];
    ## Pick a license from
    ## https://github.com/NixOS/nixpkgs/blob/master/lib/licenses.nix
    # license = licenses.mit;
  };
}
